HOST = "localhost"
PORT = 8000
HTTPS = True

# DYNAMIC_CLIENT_REGISTRATION_PORT_RANGE_MIN = 8001
# DYNAMIC_CLIENT_REGISTRATION_PORT_RANGE_MAX = 8500
#
# STATIC_CLIENT_REGISTRATION_PORT_RANGE_MIN = 8501
# STATIC_CLIENT_REGISTRATION_PORT_RANGE_MAX = 9000

DYNAMIC_CLIENT_REGISTRATION_PORT_RANGE_MIN = 8001
DYNAMIC_CLIENT_REGISTRATION_PORT_RANGE_MAX = 8002

STATIC_CLIENT_REGISTRATION_PORT_RANGE_MIN = 8501
STATIC_CLIENT_REGISTRATION_PORT_RANGE_MAX = 8502

if HTTPS:
    BASE = "https://%s:%d/" % (HOST, PORT)
else:
    BASE = "http://%s:%d/" % (HOST, PORT)

# If BASE is https these has to be specified
SERVER_CERT = "certs/server.crt"
SERVER_KEY = "certs/server.key"
CA_BUNDLE = None

STATIC_CLIENT_REGISTRATION_PORTS_DATABASE_FILE = "./static_ports.db"

OPRP_SSL_MODULE = "sslconf"

OPRP_TEST_FLOW = "tflow"

CONFIG_MAX_NUMBER_OF_CHARS_ALLOWED = 10000